import "./globals.css";
import { Roboto } from 'next/font/google'
import Navbar from "../app/Componend/Navbar/headers";
const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})

export const metadata = {
  title: "Protfolio website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
